from ubuntu

#COPY run.sh /run.sh
COPY docker_setup.sh /docker_setup.sh
COPY start_docker.sh /start_docker.sh
#ARG LOOPS
#ENV CONT_IMG_VER v1.0.0
#RUN echo $CONT_IMG_VER

#CMD ["bash","docker_setup.sh"]
CMD ["bash","start_docker.sh"]
